### ISSUE TITLE
Allow searching with multiple search engines at the same time

### ISSUE THREAD

**Issue by simonbcn** [emvaized/selecton-extension#12]
In my case I sometimes need to search for the same word/phrase in several search engines. It would be very convenient to be able to do it in one go instead of having to select the text, press search, go back to the page, select again and press search again.

**Comment by emvaized** [comment]
Thanks for your suggestion.
In the current version you already can open search links in background tabs (eg. without switching to them), by clicking with middle mouse button (basically press on scroll wheel) instead of the left button. 

I guess I should also consider adding an option to not hide the tooltip in this case.

**Comment by simonbcn** [comment]
Even if I open the window in the background, the tooltip closes and I still have to select the text again for it to be shown again.

**Comment by emvaized** [comment]
After new update 3.3.8, please use "Panel behavior > Middle click (to open in background) hides panel" — unticking this should provide the behavior you requested
