### ISSUE TITLE
Unit and time conversion issues

### ISSUE THREAD

**Issue by sbozdemir** [emvaized/selecton-extension#13]
Hey there! This is a great add-on, good job with that.

Only drawback I've experienced with is unit and time conversions. Currency conversions seems working fine. I used the site given below for testing different units and time zones and most of them failed. 

Test site: https://blogs.opera.com/desktop/2017/08/time-zone-unit-converters-highlight-opera-48-beta-release/

Also working time conversions displays results in 12Hour format and sometimes with colon(":") sign at the end of it.  It is a bit confusing. Can you represent them in 24 Hour format or add am/pm indicator?

Thank you for the hard work.

![Screenshot 2021-11-03 145054](https://user-images.githubusercontent.com/41501117/140055830-fae47cdf-0722-4d67-96d4-37bdbf29cb0d.png)

**Comment by emvaized** [comment]
Thanks for your feedback and kind words!
Yes, I would say time convert button is currently the most unreliable amongst all. In order for it to work time text should be in precise format, so that for example "2:00 PM" would be recognized, and "2:00pm" would not be. 

Yesterday I uploaded new update 3.3.9, which includes some improvements for the time button algorythm — it should improve the situation a bit:
![изображение](https://user-images.githubusercontent.com/37851576/140089551-5326ae7c-6d2b-4214-a902-83d1c1e7f0ec.png)

This update is already available on Firefox, and should be approved for Chrome within few days. But I would say this feature is still far from perfect, and still relies a lot for text to be in standard time format.

Actually, a lot of timezones from this page are not even currently [supported](https://github.com/emvaized/selecton-extension/blob/527993e7290811aa9e5fb116215fe28f9e2daf91/src/data/keywords.js#L194) by Selecton. So thanks for sharing, I will add them now.

**Comment by emvaized** [comment]
In past few updates I improved unit and time recognition, so now it handles >70% of use cases on mentioned page, except some rare ones which I decided not to add for better performance of the extension.

Please feel free to reopen this if bad unit recognition will still be the case for you in everyday use.
