### ISSUE TITLE
Triple clicking URL text does not open the go to link option

### ISSUE THREAD

**Issue by jupiter104** [emvaized/selecton-extension#21]
Sometimes I see links on some websites that are not clickable, meaning only the text is there like this.

github.com/emvaized/selecton-extension

When I triple click it, all the text gets selected but Selecton does not show the option to go to that link.
However, if I manually click and drag to select the URL text, Selecton shows the go to that link option.
Would be great if it also worked when you triple clicked on the URL text. Also, notice if the www. isn't there in the beginning, it doesn't work. Not really a huge issue but I thought I'd mention it anyway.

**Comment by emvaized** [comment]
Triple click will most likely never properly supported due to the mouse listeners Selecton relies on, see here: https://github.com/emvaized/selecton-extension/issues/15#issuecomment-982049542

As for links, the script currently searches for '://' symbol, not the 'www' one - hence this link is not recognized. It was the idea to not rely on the local domains, as there may be countless variants of them.
However, there could be added a check for the most generic ones, like '.com'

**Comment by jupiter104** [comment]
Yeah like I said, it's not a big deal. Many people don't even know about triple click, lol.

**Comment by emvaized** [comment]
Link recognition should be improved in new version 3.5.0
