### ISSUE TITLE
Any idea if the extension could work for PDFs and iframes?

### ISSUE THREAD

**Issue by waldenn** [emvaized/selecton-extension#23]
Hi, thanks for a great extension!

I was wondering if someone knows if it is possible (or maybe impossible) that this extension could work with:

- The **browsers internal PDF viewer** (eg. for Chromium and Firefox). Not sure if access to the text-selection is currently technically possible. If not, I think submitting an issue for this to the browser repo's might be worth a try.

- **Self-hosted iframes** (same-domain, etc). Looking [here](https://stackoverflow.com/questions/8917593/do-chrome-extensions-access-iframes), this would seem to be the case for all iframes (not just local ones), when `"all_frames": true` is set in the manifest.json file.

I actually would love to be able to use this extension in these situations.

**Comment by emvaized** [comment]
Hi @waldenn 

As for the first one, I think it's not possible for the same reason tooltip is not available on new tab page, extensions store, service browser pages (like browser settings page) etc. - external browser extensions are denied access to them for security means. There's a lot of malicious extensions out there, which could do quite bad things had they access to these service pages - therefore I doubt this policy will change anytime in the future, and I doubt if it really should.

As for iframes access — that's actually a great idea. I even tried that already, and it seems working just fine. 
Aren't you aware if `all_frames` permission comes with any caveats or performance degradation?

**Comment by waldenn** [comment]
Hey Max. thanks for the response.

I'll look a bit further into the first point soon, as I'am not yet fully convinced it should impossible or unsafe if there was a small API for that text-selection data. I may be wrong though.

Regarding the iframe access I don't think this should cause any performance issues. Looks like a great added feature to me too, looking forward to using it : )

**Comment by emvaized** [comment]
1. Sure, let me know if you'll find something interesting about it

2. Okay, then I'll run it for a while with this permission and test how it works, and if I won't find any issues this will be added in next version. Thanks for this idea!

3. Sure, any forks are welcomed. To get the most essential functionality you would mainly need tooltip.js and some parts of index.js, as well as certain styles from index.css - and some corrections may be needed to make it run on a website instead of an extension. But in general it should work just fine.

But keep in mind that I'm currently working on big project refactor, therefore project and code structure may change anytime soon. Maybe I'll push it in `dev` branch first, as it's not fully stable yet.

4. Yes, there's a link for donations – it's somewhat ugly, but works :)
https://emvaized.diaka.ua/donate

**Comment by waldenn** [comment]
> 1. Sure, let me know if you'll find something interesting about it

I'll post a message in this issue, when I have something. Don't have time to look into it currently,  but will at some point.

>     2. Okay, then I'll run it for a while with this permission and test how it works, and if I won't find any issues this will be added in next version. Thanks for this idea!

Nice!

>     3. Sure, any forks are welcomed. To get the most essential functionality you would mainly need `tooltip.js` and some parts of `index.js`, as well as certain styles from `index.css` - and some corrections may be needed to make it run on a website instead of an extension. But in general it should work just fine.
>        But keep in mind that I'm currently working on big project refactor, therefore project and code structure may change anytime soon. Maybe I'll push it in `dev` branch first, as it's not fully stable yet.

Thanks for the heads-up! Not starting this extension work yet, just trying to explore the idea for now. Once I start, I'll try to keep my patch as minimal as possible.

>     4. Yes, there's a link for donations – it's somewhat ugly, but works :)
>        https://emvaized.diaka.ua/donate

Will donate soon. Thank you!

**Comment by waldenn** [comment]
> > 4. Yes, there's a link for donations – it's somewhat ugly, but works :)
> >    https://emvaized.diaka.ua/donate`
> 
> Will donate soon. Thank you!

Hey, I tried to donate, but my bank / credit card did not allow this transaction. Do you have some crypto-coin wallet I could send to? You can email me at jama at conze . pt

**Comment by emvaized** [comment]
@waldenn Sorry for this confusion. No, unfortunately I don't own crypto wallet, and can't use Patreon or Github Sponsors because PayPal doesn't work in my country, as well as most donation services which use it under the hood. That's why I had to stick to this weird 3rd party service, which doesn't even allow to create a proper English page, while taking a huge 10% commission from every donation.

**Comment by waldenn** [comment]
> @waldenn Sorry for this confusion. No, unfortunately I don't own crypto wallet, and can't use Patreon or Github Sponsors because PayPal doesn't work in my country, as well as most donation services which use it under the hood. That's why I had to stick to this weird 3rd party service, which doesn't even allow to create a proper English page, while taking a huge 10% commission from every donation.

Ok, that is a real pity. Please let me know if you ever get something else going, eg. if you can open a crypto wallet on Coinbase or something. Crazy how segregated these systems still are and how much power these US players have in it.

**Comment by emvaized** [comment]
Hi @waldenn 
I returned to this thread by chance, remembered about your message, and just wanted to let you know that I now have a working PayPal wallet linked to my email (maximtsyba@gmail.com).

I also created Ko-Fi page ([https://ko-fi.com/emvaized](https://ko-fi.com/emvaized)), but seems it may reject transactions for some reason. So if it's still relevant to you, you can now use PayPal
