### ISSUE TITLE
[Enhancement] Option for a key to activate the menu in text fields

### ISSUE THREAD

**Issue by simonbcn** [emvaized/selecton-extension#34]
Sometimes the menu in text fields is annoying and not necessary. I think it would be useful to be able to use a key (e.g. `Ctrl`) in combination with the left mouse button click to only activate this menu in text fields in that case.

**Comment by emvaized** [comment]
I agree that it may be annoying – that's why I left this text fields functionality disabled by default. 

But your idea with Ctrl key – doesn't it ruin the idea of keyboard-less experience with the tooltip? I mean, if you're comfortable with reaching out to Ctrl key to reveal the tooltip, then it shouldn't be a problem to also hit Ctrl+C, Ctrl+V or any other hotkey, thus making the tooltip redundant.

**Comment by simonbcn** [comment]
I disagree, we are talking only in the case of text fields and it is not the same having to release the mouse and move your hands to press a combination of 2 keys than simply pressing one (<i>with the free hand</i>) while the other is still on the mouse.

**Comment by emvaized** [comment]
But pressing Ctrl+C, Ctrl+X and Ctrl+V (3 main tooltip buttons for fields) requires only one hand, no need to release the mouse. For example, I usually press these hotkeys with the pinky and index fingers.

Or you meant that you're not physically able to press these hotkeys with one hand?
