### ISSUE TITLE
shortcut keys to do task quickly

### ISSUE THREAD

**Issue by RitikDixit2** [emvaized/selecton-extension#36]
Could you add "shortcut keys" as well like for "Highlight" option and "copy page link to the selected text" option. it would be Amazing  Thanks for this wonderful  extension

**Comment by emvaized** [comment]
Thanks for your suggestion. I would say, shortcuts support would be quite a complex thing, and I'm not sure how reasonable it is to develop for an extension initially indented for mouse-oriented users...

However, I can think of an easier solution to this – add ability to trigger buttons from keyboard based on their index, e.g. Ctrl + 1 to click the first button, Ctrl + 2 for the second button, and so on – with displaying a visual hint over them or something... But I'm not sure how well it could satisfy your request

**Comment by emvaized** [comment]
I'm closing this issue now due to inactivity.

If you only consider this as a way to perform these actions quicker, maybe it would help you to change `Behavior` > `Max buttons to show in the tooltip` > `5` or more, so that these buttons will not get hidden under "More" button and become more easily accessible. In this case you may also like to change `Appearance` > `Buttons style` to `Icons only` for a more compact view.
<img width="365" alt="screenshot" src="https://user-images.githubusercontent.com/37851576/192182438-43bef4fd-c88d-4c30-ad0a-96c702145675.png">
