### ISSUE TITLE
Suggestion/Request

### ISSUE THREAD

**Issue by Tw3ak3rz** [emvaized/selecton-extension#39]
I'm not having an actual problem, but it is sort of an issue.

The dictionary function almost always fails to produce a definition. Any chance that you can use dictionary.com or some other reference to check for definitions? You use Wikipedia currently it seems, hopefully there is a better option that works more often you can implement.

Thank you, this is one of the best extensions in terms of usefulness and I'm glad to have stumbled across it on reddit when you first released it.

**Comment by emvaized** [comment]
Thanks for your kind words! 

Yeah, Dictionary button currently uses Wikipedia. To be more precise, it uses [prop=extracts](https://www.mediawiki.org/wiki/Extension%3aMobileFrontend#prop.3Dextracts) API. 

This choice is reasoned because it's free, has a lot of info (not only words definitions, but also info on popular people, companies etc), and also supports multiple languages (Dictionary buttons tries to fetch info on user's language first). I'm not aware of any other publicly available and free API which can do all of that.

**Comment by Tw3ak3rz** [comment]
You're welcome. 

I just hoped there was a way to look at other sources but I assumed it wouldn't be likely.

Thanks again!
