### ISSUE TITLE
[Feature Request] Usage of Firefox/browser search engines as Selecton search engines

### ISSUE THREAD

**Issue by BthereDthat** [emvaized/selecton-extension#54]
It would be nice to be able to synchronize Selecton search engines list with browser one. IMVHO that option might even be the default one...

It looks like possible at first glance:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/search

**Comment by emvaized** [comment]
I considered integrating this option initially, but the problem is - this API is supported only in Firefox, and not in Chrome or it's derivates, which makes up about 4/5 of the total user base. And since my initial goal was to have the same userbase and feature set among all browsers, this idea was declined

**Comment by BthereDthat** [comment]
OK :|
