### ISSUE TITLE
CTRL Hotkey to Trigger Panel Re-open

### ISSUE THREAD

**Issue by megamorphg** [emvaized/selecton-extension#56]
Sometimes I highlight something and then the pop-up goes away because I accidentally press a key (or for some other reason).

Currently there doesn't seem to be a a way to easily retrigger the pop-up. Can we make it so that if the panel isn't selected we can double-press CTRL to re-trigger it? Hopefully this wouldn't interfere with the existing feature to hold CTRL as we highlight to disable word-snapping.

**Comment by emvaized** [comment]
Hi! Sorry for long response. 
I'm not sure how much utility such function will actually bring. This extension was initially conceived as a way to make using the computer easier when you're in "mouse only" mode, so that you can easily perform various operations without the need to reach the keyboard. And in this use case, most of the times it is easier to simply re-select the select to view the popup again. 

The cases when you would need a hotkey to show the popup again seems too rare to me to justify the development of shortcuts support

**Comment by emvaized** [comment]
@megamorphg 
As far as I remember, there were technical difficulties to add this option, so there's only "Recreate tooltip after scroll or window resize" option, which shows tooltip again after scroll is completed. Basically it should function the same as an option to not hide pop-up when scrolling
