### ISSUE TITLE
Frustrating Discord bug... (With Screenshot)

### ISSUE THREAD

**Issue by PhoenixEugene** [emvaized/selecton-extension#58]
Hello there. First of all, thank you so much for developing such a useful and feature-rich extension, it's truly wonderful. Although, I sincerely hope it hasn't been abandoned.

A few minutes after I installed the extension for the first time, I opened my discord (web version), and a frustrating little bug presented itself after selecting a few words to copy:

![2023-06-13](https://github.com/emvaized/selecton-extension/assets/54819253/edc08e2e-6575-45c8-9a15-5bb3602b36f4)

As you can see, for some reason the borders separating the options are gone and the text gets smushed together into one big word. Additionally, other things seem to be broken on Discord as well: I have Google and DuckDuckGo both set as search methods, yet when I hover over the 'search' option, neither shows up. I also have the "**_Remove text selection after selected action_**" set to true and that doesn't work either. When I click copy, for example, the selected text stays selected and the popup menu doesn't disappear.
The extension so far seems to be working perfectly on every other website I've visited. So hopefully this is a simple issue that can be easily fixed!

Thank you so much!

(Ps: One other nitpick if that's ok: When I select a word or a sentence in a text field and I delete it/replace it, the popup menu stays visible until I click somewhere else. Would it be possible to have it disappear the moment I delete/replace a selection?)

**Comment by emvaized** [comment]
Hi Eugene!
Thanks for your kind words, really appreciated.

Unfortunately I don't actively develop Selecton due to the lack of time and
inspiration – therefore not sure when I'll be able to investigate your
issue. Maybe enabling "Apply configs immediately" in the extension settings
could resolve the problem?

Regards,
Max


ср, 14 июн. 2023 г., 00:58 Eugene ***@***.***>:

**Comment by PhoenixEugene** [comment]
@emvaized Thank you so much for the reply! Ticking the "Apply configs immediately" option actually did fix the Discord issue! Again, thank you!

**Comment by emvaized** [comment]
I just uploaded new version 3.7.0, in which this problem might be fixed, because the popup styles are now loaded right before it will be shown (instead of only on initial page load). I also added a note in FAQ about ticking "Apply configs immediately" option if any compatibility problems accur.

Closing this issue now
