### ISSUE TITLE
Currency conversion is not working correctly for TRY

### ISSUE THREAD

**Issue by sbozdemir** [emvaized/selecton-extension#59]
This feature used to work fine, but since the last updates it has been converting incorrectly. It might be due to API you are using [exchangerate.host](https://exchangerate.host/#/). 

I also noticed that you have changed the minimum rate update interval (days) to 3 but mine was still 1 (the value before the change was applied). I changed it to 3 days but nothing changed. It might be also related to that.

**Comment by emvaized** [comment]
Thanks a lot for reporting, and sorry for long response! 
Too sad that they decided to change API and limited free API requests only to 100 per day. This API doesn't fit anymore to Selecton, as we currently have over 2000 users. 

I just published a new version 3.7.0, in which API source was changed to fawazahmed0's [currency-api](https://github.com/fawazahmed0/currency-api?tab=readme-ov-file). I hope it will work fine for now. Minimal update rate was also increased to 7, in order to reduce possible load on our new API — let's hope it will help it to stay free for as long as possible.
