### ISSUE TITLE
Displaying translation

### ISSUE THREAD

**Issue by Articmar** [emvaized/selecton-extension#64]
Please add an option that when you click on the "Translate" button, instead of opening a new tab, the translation of all selected text will be displayed in a popup window, similar to how it works in the extension "TWP - Translate Web Pages".

**Comment by emvaized** [comment]
Thanks for your suggestion. 
It is already possible to see the translation in the popup when hovering the "Translate" button, for this to work the "Live translation" option should be enabled in the extension settings. 

For option to open pages in a popup window on click instead of a new tab, please refer to the existing request https://github.com/emvaized/selecton-extension/issues/57

**Comment by ubless607** [comment]
@emvaized Is the translate working properly in the lastest version?
